"""empty message

Revision ID: d698c2dd3d1c
Revises: e9e83e3dc461
Create Date: 2025-05-13 23:59:02.869261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd698c2dd3d1c'
down_revision = 'e9e83e3dc461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogpost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('author', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('img_post_view', sa.String(length=255), nullable=True),
    sa.Column('image_mime_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('blogposts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogposts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), nullable=False),
    sa.Column('author', sa.VARCHAR(length=50), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('img_post_view', sa.VARCHAR(length=255), nullable=True),
    sa.Column('image_mime_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('blogpost')
    # ### end Alembic commands ###
